### ISSUE TITLE
TileEntity IUpdatePlayerListBox

### ISSUE THREAD

**Issue by BitForger** [KaminoCoding/Soul-Fragments#1]
Why/What on earth does it do and where did it go? I tried looking through minecraft source and don't see it in MC 1.8.9. Was it in 1.8? I'm just wondering.

**Comment by Cyb3rWarri0r8** [comment]
@TheCool1James

**Comment by TeNNoX** [comment]
Was refactored to ITickable ;)

**Comment by BitForger** [comment]
@TeNNoX Thanks

**Comment by TheCool1James** [comment]
I had nearly forgot about you guys xD
Hello. And yea it was refractored.

**Comment by TeNNoX** [comment]
But be careful to use the `net.minecraft.util` one - the other one is for textures. 
Caused me a lot of pain :/
